shared:
  image: 'node:9.5.0-slim'
jobs:
  main:
    requires:
      - ~commit
    steps:
      - { install: 'npm install' }
      - { test: 'npm test' }
  dev:
    requires:
      - ~commit
    steps:
      - { install: 'npm install' }
      - { test: 'npm test' }
jenkins:
  host: 'http://jenkins02.betaskope.local'
  port: 8080
  username: pgula
  password: Netskope@2141
